<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <LangVersion>default</LangVersion>
        <!-- Disable code analysis for test-support code -->
        <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
        <EnableNETAnalyzers>false</EnableNETAnalyzers>
        <AnalysisMode>None</AnalysisMode>
        <RunAnalyzers>false</RunAnalyzers>
        <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
        <RunAnalyzersDuringLiveAnalysis>false</RunAnalyzersDuringLiveAnalysis>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);CS1591;SA1600</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DKNet.Svc.BlobStorage.Abstractions" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
        <PackageReference Include="Testcontainers.MsSql" />
        <PackageReference Include="Testcontainers.PostgreSql" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.Extensions.DependencyInjection"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DKNet.StaticData.Api\DKNet.StaticData.Api.csproj" />
    </ItemGroup>

</Project>
